## AWS CodeDeploy 설정

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes

permissions:
  - object: /
    pettern: "**"
    owner: ec2-user
    group: bmart-group

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user