## AWS CodeDeploy 설정

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes
  - source: docker-compose.yml  # Docker Compose 파일을 추가합니다.
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: /scripts/deploy.sh
      timeout: 60
      runas: ec2-user