# nginx.Dockerfile

# 1. Nginx의 최신 공식 이미지 사용
FROM nginx:latest

# 2. 로컬의 nginx.conf 파일을 컨테이너의 Nginx 설정 파일로 복사
COPY ./nginx.conf /etc/nginx/nginx.conf

# 3. 로컬의 정적 파일을 Nginx의 기본 웹 루트 디렉토리로 복사
COPY ./public /usr/share/nginx/html

# 4. Nginx가 기본적으로 사용하는 포트 80 개방
EXPOSE 80
