version: '3'

services:

  bmart-app:
    container_name : bmart-app
    image: kimgyeongha/bmart-app:develop
    environment:
      SPRING_REDIS_HOST: redis

  nginx:
    container_name : bmart-nginx
    image: kimgyeongha/nginx-app:develop
    ports:
      - "80:80"
    depends_on:
      - bmart-app

  redis:
    container_name: bmart-redis
    image: redis:latest
    ports:
      - "6379:6379"

